//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppServices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfAppServices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t pause service because the service with name &apos;{0}&apos; doesn&apos;t exist.
        /// </summary>
        internal static string ManageServiceStatus_ArgumentException_Pausing {
            get {
                return ResourceManager.GetString("ManageServiceStatus_ArgumentException_Pausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start service because the service with name &apos;{0}&apos; doesn&apos;t exist.
        /// </summary>
        internal static string ManageServiceStatus_ArgumentException_Running {
            get {
                return ResourceManager.GetString("ManageServiceStatus_ArgumentException_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t stop service because the service with name &apos;{0}&apos; doesn&apos;t exist.
        /// </summary>
        internal static string ManageServiceStatus_ArgumentException_Stopping {
            get {
                return ResourceManager.GetString("ManageServiceStatus_ArgumentException_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported managing status command: {0}. Available commands: run, pause and stop.
        /// </summary>
        internal static string ManageServiceStatus_ArgumentException2 {
            get {
                return ResourceManager.GetString("ManageServiceStatus_ArgumentException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t pause &apos;{0}&apos; service.
        /// </summary>
        internal static string ManageServiceStatus_Exception_Pausing {
            get {
                return ResourceManager.GetString("ManageServiceStatus_Exception_Pausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start &apos;{0}&apos; service.
        /// </summary>
        internal static string ManageServiceStatus_Exception_Running {
            get {
                return ResourceManager.GetString("ManageServiceStatus_Exception_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t stop &apos;{0}&apos; service.
        /// </summary>
        internal static string ManageServiceStatus_Exception_Stopping {
            get {
                return ResourceManager.GetString("ManageServiceStatus_Exception_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation. Description: {0}.
        /// </summary>
        internal static string ManageServiceStatus_InvalidOperationException {
            get {
                return ResourceManager.GetString("ManageServiceStatus_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time out of waiting for changing service status. Unknown status of operation.
        /// </summary>
        internal static string ManageServiceStatus_TimeoutException {
            get {
                return ResourceManager.GetString("ManageServiceStatus_TimeoutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausing &apos;{0}&apos; service....
        /// </summary>
        internal static string ServiceTaskDesc_Paused {
            get {
                return ResourceManager.GetString("ServiceTaskDesc_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running &apos;{0}&apos; service....
        /// </summary>
        internal static string ServiceTaskDesc_Running {
            get {
                return ResourceManager.GetString("ServiceTaskDesc_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping &apos;{0}&apos; service....
        /// </summary>
        internal static string ServiceTaskDesc_Stopped {
            get {
                return ResourceManager.GetString("ServiceTaskDesc_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something goes wrong during updating list of services. If the error is continueing repeats, try to restart application..
        /// </summary>
        internal static string UpdateServices_Exception {
            get {
                return ResourceManager.GetString("UpdateServices_Exception", resourceCulture);
            }
        }
    }
}
